### ISSUE TITLE
Create an intro notebook

### ISSUE THREAD

**Issue by WesleyTheGeolien** [ClimateMatchAcademy/course-content#1]
We need to create a tutorials intro notebook equivalent to here: https://github.com/ClimateMatchAcademy/course-compclimate/blob/main/tutorials/intro.ipynb

**Comment by Arpanio** [comment]
The link leads to a 404. I can take a look if this is still required. I'll need the updated link.

**Comment by Nat-Stein** [comment]
Resolved?
