### ISSUE TITLE
Proof-reading executable book - Sponsors image

### ISSUE THREAD

**Issue by Arpanio** [ClimateMatchAcademy/course-content#22]
In the [introduction page](https://climatematchacademy.github.io/tutorials/intro.html), I couldn't confirm if the "sponsors" image is up-to-date. I checked the [Climatematch page](https://academy.climatematch.io/about) and the [Neuromatch page](https://academy.neuromatch.io/about).

Sidenote, Neuromatch has a [supporters page](https://academy.neuromatch.io/our-support/supporters). I don't see that in the Climatematch page. Should we have a similar section there?

**Comment by earthchichi** [comment]
Our current course sponsor images are NASA TOPS and Google DeepMind. This has updated
