### ISSUE TITLE
For W1D4 tutorial 1, catch warnings: 

### ISSUE THREAD

**Issue by OhadZivan** [ClimateMatchAcademy/course-content#228]
link to slack discussion:
https://climatematch.slack.com/archives/C055VU74XLZ/p1689773544947059?thread_ts=1689773489.798669&cid=C055VU74XLZ

use `with warnings.catch_warnings():` to catch LiPD warnings `Error: Unable to update file to LiPD v1.3: dictionary keys changed during iteration`

**Comment by jlpearso** [comment]
Solved by this commit https://github.com/ClimateMatchAcademy/course-content/commit/7687b9dc02296e5b011dc5a739f9601ea5f9f37e#diff-2193b9fed23ca09aca2ffdc502e35b4d6e201ce2c6e2623e1ef56fdc1a6d8426
