### ISSUE TITLE
Proof-reading executable book - Concepts map image and the curriculum overview is from Neuromatch

### ISSUE THREAD

**Issue by Arpanio** [ClimateMatchAcademy/course-content#24]
The [concepts map](https://climatematchacademy.github.io/tutorials/intro.html#concepts-map) and [curriculum overview](https://climatematchacademy.github.io/tutorials/intro.html#curriculum-overview) sections are from Neuromatch

**Comment by earthchichi** [comment]
Concept map has been updated.
Curriculum overview has been updated
