### ISSUE TITLE
Proof reading Executable Book [Climate Future] [Climate Modeling] [W1D5]

### ISSUE THREAD

**Issue by dcbiton** [ClimateMatchAcademy/course-content#27]
[link](https://climatematchacademy.github.io/tutorials/W1D5_ClimateModeling/student/W1D5_Tutorial1.html)

1. Titles: (#Tutorial # 1 : A Simple Greenhouse Model) and (#Tutorial Objectives) are not formatted well
2. No video yet under Lecture 
3. py file of the solution is not yet working [link to the solution](https://github.com/NeuromatchAcademy/course-content/tree/main//tutorials/W1D5_ClimateModeling/solutions/W1D5_Tutorial1_Solution_aec552c3.py)

**Comment by earthchichi** [comment]
All problems will be sorted and addressed in the `mega issue`
