### ISSUE TITLE
Remove google colab links in W2D5 notebooks

### ISSUE THREAD

**Issue by WesleyTheGeolien** [ClimateMatchAcademy/course-content#35]
![image](https://github.com/ClimateMatchAcademy/course-content/assets/18068320/982132e7-7e02-4c11-a568-192affb0986a)

**Comment by jlpearso** [comment]
@WesleyTheGeolien can I ask why you wanted to remove these?

**Comment by WesleyTheGeolien** [comment]
These were from before I added them all in, as you can see there is only colab and not kaggle this would/should have been addressed if colab and kaggle are present in the latest book
